spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/global_tech_blog_archive}
    username: ${DB_USERNAME:archive_user}
    password: ${DB_PASSWORD:archive_password}
  jpa:
    hibernate:
      ddl-auto: update
