spring:
  application:
    name: global-tech-blog-archive
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: "crawl/crawl-parser.yml"

server:
  port: ${SERVER_PORT:8080}

crawl:
  scheduler:
    enabled: ${CRAWL_SCHEDULER_ENABLED:false}
    cron: "${CRAWL_SCHEDULER_CRON:0 0 3 * * *}"
    zone: ${CRAWL_SCHEDULER_ZONE:Asia/Seoul}
